import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react"; // Ensure /react is imported

export const apiUrl = process.env.NEXT_PUBLIC_API_URL;

export const Api = createApi({
  reducerPath: "Api",
  baseQuery: fetchBaseQuery({
    baseUrl: apiUrl,
  }),
  tagTypes: ["api"],
  endpoints: (builder) => ({
    addContactUsForm: builder.mutation<any, any>({
      query: (data) => {
        const formData = new FormData();
        formData.append("name", data?.name);
        formData.append("email", data?.email);
        formData.append("message", data?.message);
        formData.append("mobile", data?.mobile);
        formData.append("uuid", data?.uuid);
        return {
          url: "v2/contact-us/add",
          method: "POST",
          body: formData, // Use formData as body
        };
      },
    }),
  }),
});

// Correct hook name generated by createApi
export const {useAddContactUsFormMutation} = Api;
    