import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react"; // Ensure /react is imported

export const apiUrl = process.env.NEXT_PUBLIC_API_URL;

export const Portfolio_Api = createApi({
  reducerPath: "Portfolio_Api",
  baseQuery: fetchBaseQuery({
    baseUrl: apiUrl,
  }),
  tagTypes: ["Portfolio"],
  endpoints: (builder) => ({
    getAllPortfolio: builder.query<
      any,
      {
        categorie?: any;
        rowsPerPage?: number;
        page?: number;
      } | void
    >({
      query: (filters) => {
        const params: Record<string, string | number | boolean> = {};
        // Add filters to the query parameters if they are present
        if (filters) {
          if (filters.categorie) {
            params.categorie = filters.categorie; // Convert number to string
          }
          if (filters.rowsPerPage) {
            params.rowsPerPage = filters.rowsPerPage; // Convert number to string
          }
          if (filters.page) {
            params.page = filters.page; // Convert number to string
          }
        }

        return {
          url: "v2/portfolio",
          params, // Use the dynamically constructed params
          method: "GET",
        };
      },
      providesTags: [{ type: "Portfolio", id: "LIST" }],
    }),
  }),
});

// Correct hook name generated by createApi
export const { useGetAllPortfolioQuery } = Portfolio_Api;
