import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react"; // Ensure /react is imported

const apiUrl = process.env.NEXT_PUBLIC_API_URL;

export const Post_Api = createApi({
  reducerPath: "Post_Api",
  baseQuery: fetchBaseQuery({
    baseUrl: apiUrl,
  }),
  tagTypes: ["Post"],
  endpoints: (builder) => ({
    getSingle: builder.query<any, string>({
      query: (id: string) => ({
        url: `v2/post/store/data/${id}`,
        method: "GET",
      }),
      providesTags: [{ type: "Post", id: "LIST" }],
    }),
    getAllPost: builder.query<
      any,
      {
        type?: string;
        rowsPerPage?: number;
        page?: number;
      } | void
    >({
      query: (filters) => {
        const params: Record<string, string | number | boolean> = {};
        // Add filters to the query parameters if they are present
        if (filters) {
          if (filters.rowsPerPage) {
            params.rowsPerPage = filters.rowsPerPage; // Convert number to string
          }
          if (filters.page) {
            params.page = filters.page; // Convert number to string
          }
        }

        return {
          url: "v2/post/store",
          params, // Use the dynamically constructed params
          method: "GET",
        };
      },
      providesTags: [{ type: "Post", id: "LIST" }],
    }),
  }),
});

// Correct hook name generated by createApi
export const {
  useGetAllPostQuery,
  useGetSingleQuery,
} = Post_Api;
